package com.github.edgar615.util.vertx.jdbc;

import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;

import com.github.edgar615.util.validation.Rule;

/**
* This class is generated by Jdbc code generator.
*
* Table : user
*
* @author Jdbc Code Generator Date 2018-04-19
*/
public class UserRule {

    /**
    * 根据数据库生成的最长长度校验
    *
    * @return Multimap<String, Rule>
    */
    public static Multimap<String, Rule> maxLengthRule() {
        Multimap<String, Rule> rules = ArrayListMultimap.create();
         rules.put("username",  Rule.maxLength(60));
         rules.put("headPic",  Rule.maxLength(1024));
         rules.put("nickname",  Rule.maxLength(16));
         rules.put("fullname",  Rule.maxLength(16));
         rules.put("mobile",  Rule.maxLength(11));
         rules.put("mobileArea",  Rule.maxLength(5));
         rules.put("mail",  Rule.maxLength(60));
         rules.put("birthday",  Rule.maxLength(10));
         return rules;
    }

    /**
    * 根据数据库生成的必填项校验。
    * 在实际接口开发中，有些必填项是没有的，例如自动生成的主键开始会设置为null
    *
    * @return Multimap<String, Rule>
    */
    public static Multimap<String, Rule> requiredRule() {
        Multimap<String, Rule> rules = ArrayListMultimap.create();
        
        rules.put("userId", Rule.required());
        return rules;
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}